name: check-repos

on:
   workflow_call:
   workflow_dispatch:

jobs:
  get-repository:

    runs-on: ubuntu-latest

    steps:
    - name: get repository
      run: echo ${{ github.repository }}
      
