# This is a basic workflow to help you get started with Actions

name: check-repos

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  jobs: 
  get-repository:
    runs-on: ubuntu-latest
    name: get repository
    steps:
      -name: get repository
      -run: echo ${{ github.repository }}
