name: Create branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  get-repository:
    runs-on: ubuntu-latest
    steps:
    - name: get repository
      run: |
        echo "${{ github.event.commits  }}";
        echo "${{ github.event.commits.length  }}";
        echo "${{ github.event.commits[0]  }}";
        echo "${{ github.event.commits[0].message  }}";
        
    - name: test 2
      uses: actions/github-script@v6
      with:
        script: |
          const commits = ${{ toJSON(github.event.commits) }}
          for (const commit of commits) {
            console.log(commit);
          }
