# This is a basic workflow to help you get started with Actions

name: minor

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure remote repository
        run: |
          git remote set-url origin "https://0nary:${{ secrets.GITHUBACCESSTOKEN }}@github.com/0nary/Test.git"
      - name : Install Versioning.NET
        run: |
          dotnet tool install --global Versioning.NET
      - name : Updating version
        run: |
          dotnet-version increment-version-with-git -h
          dotnet-version increment-version-with-git -g "." -b main
