name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
    
  get-increment:
    uses: ./.github/workflows/get-increment.yml   
    
  output-increment:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "${{jobs.get-increment.outputs.increment}}"
