name: .NET

on:
   workflow_call:
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.outputs.success }}

    steps:
    - name: set default output
      run: echo "::set-output name=success::false"
      
    - name: Setup .NET
      uses: actions/checkout@v3
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore "./TestConsoleApp.sln"
      
    - name: Build
      run: dotnet build "./TestConsoleApp.sln" --configuration Release --no-restore
      
    - name: start up MSSQL
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
            
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: test echo
      run: echo "Test"
   
    - name: update output
      run: echo "::set-output name=success::true"
