name: .NET

on:
   workflow_call:
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ outputs.success }}

    steps:
    - name: set default output
      run: ::set-output name=success::false
      
    - uses: actions/checkout@v3
    - name: test echo
      run: echo "Test"
   
    - name: update output
      run: ::set-output name=success::true
