name: .NET

on:
   workflow_call:
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.outputs.success }}

    steps:
    - name: set default output
      run: echo "::set-output name=success::false"
      
    - uses: actions/checkout@v3
    - name: test echo
      run: echo "Test"
   
    - name: update output
      run: echo "::set-output name=success::true"
